### ISSUE TITLE
FileSystemException: Failed to watch path

### ISSUE THREAD

**Issue by scheglov** [dart-lang/watcher#19]
The following exception was logged from the IDEA plugin.
It seems that watcher threw it.

Is it expected?
How should clients react on this?
Can clients/runZoned tell if it is a special type of FileSystemException from watcher other than string matching?

```
Dart analysis server, SDK version 1.13.0-dev.7.12, server version 1.12.0, FATAL error: Failed to handle request: {clientRequestTime: 1448503919387, params: {included: [/usr/local/google/home/xxxxx/greentea/google3/ads/acx2, /usr/local/google/home/xxxxx/greentea/google3/crm/greentea/fe2, /usr/local/google/home/xxxxx/greentea/google3/crm/greentea/fe3, /usr/local/google/home/xxxxx/greentea/google3/third_party/dart/angular2], excluded: [/usr/local/google/home/xxxxx/greentea/google3/crm/greentea/fe2/.idea, /usr/local/google/home/xxxxx/greentea/google3/crm/greentea/fe2/out, /usr/local/google/home/xxxxx/greentea/google3/crm/greentea/fe2/out, /usr/local/google/home/xxxxx/greentea/google3/crm/greentea/fe2/out, /usr/local/google/home/xxxxx/greentea/google3/crm/greentea/fe2/out], packageRoots: {}}, method: analysis.setAnalysisRoots, id: 3}
FileSystemException: Failed to watch path, path = '/usr/local/google/home/xxxxx/greentea/google3/third_party/dart/angular2/lib/src/platform/browser/debug' (OS Error: No such file or directory, errno = 2)
#0      AnalysisServer.sendServerErrorNotification (package:analysis_server/src/analysis_server.dart:913)
#1      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:715)
#2      _rootRunBinary (dart:async/zone.dart:930)
#3      _CustomZone.runBinary (dart:async/zone.dart:818)
#4      runZoned.<anonymous closure> (dart:async/zone.dart:1220)
#5      _CustomZone.handleUncaughtError (dart:async/zone.dart:784)
#6      _nullErrorHandler (dart:async/stream_impl.dart:575)
#7      _rootRunBinary (dart:async/zone.dart:926)
#8      _CustomZone.runBinary (dart:async/zone.dart:818)
#9      _CustomZone.runBinaryGuarded (dart:async/zone.dart:724)
#10     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#11     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:374)
#12     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:279)
#13     _SyncBroadcastStreamController._sendError.<anonymous closure> (dart:async/broadcast_stream_controller.dart:396)
#14     _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:331)
#15     _SyncBroadcastStreamController._sendError (dart:async/broadcast_stream_controller.dart:395)
#16     _BroadcastStreamController.addError (dart:async/broadcast_stream_controller.dart:267)
#17     _rootRunBinary (dart:async/zone.dart:926)
#18     _CustomZone.runBinary (dart:async/zone.dart:818)
#19     _CustomZone.runBinaryGuarded (dart:async/zone.dart:724)
#20     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358)
#21     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:374)
#22     _DelayedError.perform (dart:async/stream_impl.dart:606)
#23     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:711)
#24     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:671)
#25     _rootRun (dart:async/zone.dart:903)
#26     _CustomZone.run (dart:async/zone.dart:802)
#27     _CustomZone.runGuarded (dart:async/zone.dart:708)
#28     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#29     _rootRun (dart:async/zone.dart:907)
#30     _CustomZone.run (dart:async/zone.dart:802)
#31     _CustomZone.runGuarded (dart:async/zone.dart:708)
#32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#34     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#35     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:150)
```

**Comment by Blasanka** [comment]
@scheglov How did you solved this?
