### ISSUE TITLE
strong mode issue in package:watcher

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/watcher#58]
When run from the analysis server, we see:

```
type '_InternalLinkedHashMap<String, Set<dynamic>>' is not a subtype of type 'Map<String, Set<FileSystemEvent>>'
#0      _MacOSDirectoryWatcher._sortEvents (package:watcher/src/directory_watcher/mac_os.dart:207:12)
#1      _MacOSDirectoryWatcher._onBatch (package:watcher/src/directory_watcher/mac_os.dart:115:5)
#2      _rootRunUnary (dart:async/zone.dart:1134:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257:7)
#7      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#8      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#9      BatchedStreamTransformer.bind.<anonymous closure>.<anonymous closure> (package:watcher/src/utils.dart:92:14)
#10     _rootRun (dart:async/zone.dart:1122:38)
#11     _CustomZone.run (dart:async/zone.dart:1023:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#17     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#18     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#19     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by devoncarew** [comment]
This will block moving to dart 2 in the sdk (https://github.com/dart-lang/sdk/issues/33189).

**Comment by devoncarew** [comment]
I'll verify that this wasn't from running a slightly older build of the analysis server (w/o the latest package:watcher).
