### ISSUE TITLE
Failed assertion: line 152 pos 18: '!event.isDirectory': is not true. on macos

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/watcher#79]
watcher: ^0.9.7+13 on a macOS flutter desktop debug build

[✓] Flutter (Channel dev, v1.14.4, on Mac OS X 10.15.3 19D76, locale de-DE)
    • Flutter version 1.14.4 at /Users/valauskasmodestas/Desktop/flutter
    • Framework revision 5e1000cd85 (5 weeks ago), 2020-01-23 13:27:01 -0800
    • Engine revision 83a64b7233
    • Dart version 2.8.0 (build 2.8.0-dev.3.0 ef0c7f16e6)

```
 Unhandled Exception: 'package:watcher/src/directory_watcher/mac_os.dart': Failed assertion: line 152 pos 18: '!event.isDirectory': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
#2      _MacOSDirectoryWatcher._onBatch.<anonymous closure> (package:watcher/src/directory_watcher/mac_os.dart:152:18)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#4      _MacOSDirectoryWatcher._onBatch (package:watcher/src/directory_watcher/mac_os.dart:115:24)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#10     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#11     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#12     BatchedStreamTransformer.bind.<anonymous closure>.<anonymous closure> (package:watcher/src/utils.dart:41:14)
#13     _rootRun (dart:async/zone.dart:1122:38)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#20     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#21     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#22     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

I'll add more info if I catch the file that caused this.

**Comment by natebosch** [comment]
Added a bit more detail in https://github.com/dart-lang/watcher/pull/88

**Comment by modulovalue** [comment]
This seems to be fixed.
